name: Kj√∏r ende-til-ende-tester ved pull-request

on:
  pull_request:

jobs:
  should-run-end-to-end-tests:
    if: github.repository != 'navikt/dittnav' && github.repository != 'navikt/dittnav-eventer-modia'
      && github.repository != 'navikt/dittnav-kafka-backup-reader' && github.repository != 'navikt/dittnav-nightly-usage-statistics-reporter'
        && github.repository != 'navikt/innloggingsstatus' && github.repository != 'navikt/pb-workflow-authority'
        && github.repository != 'navikt/dittnav-periodic-metrics-reporter' && github.repository != 'navikt/pb-oidc-provider-gui'
        && github.repository != 'navikt/mine-saker' && github.repository != 'navikt/mine-saker-api'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

  run-end-to-end-tests:
    needs: should-run-end-to-end-tests
    runs-on: ubuntu-latest
    steps:
      - name: 'Sjekk ut koden for dette repo-et'
        uses: actions/checkout@v2

      - name: 'Sjekk ut dittnav-docker-compose'
        uses: actions/checkout@v2
        with:
          repository: navikt/dittnav-docker-compose
          path: dittnav-docker-compose
          token: ${{ secrets.DOCKER_PKG_TOKEN }}

      - uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - uses: actions/setup-java@v1
        with:
          java-version: '13'

      - name: 'Pull dittnav-docker-compose'
        run: |
          echo "${{ secrets.DOCKER_PKG_TOKEN }}" | docker login --username "x-access-token" --password-stdin https://docker.pkg.github.com
          cd dittnav-docker-compose
          docker-compose pull
          cd ..

      - name: 'Docker build and tag latest'
        run: |
          ./gradlew clean assemble
          APP_NAME=$(echo $GITHUB_REPOSITORY | rev | cut -f1 -d"/" | rev )
          IMAGE_BASE="docker.pkg.github.com/$GITHUB_REPOSITORY/$APP_NAME"
          IMAGE_LATEST="$IMAGE_BASE:latest"
          docker build --tag $IMAGE_LATEST .

      - name: 'Run end-to-end-tests'
        run: |
          cd dittnav-docker-compose
          ./gradlew test
